#!/bin/sh

xrdb $HOME/.Xresources
xsetroot -solid grey
#x-terminal-emulator -geometry 80x24+10+10 -ls -title "$VNCDESKTOP Desktop" &
#x-window-manager &
# Fix to make GNOME work
export XKL_XMODMAP_DISABLE=1
/home/pi/Mac/MinivMac_Scaled/minivmac -r /home/pi/Mac/Shared/Mac-IIcx.ROM /home/pi/Mac/Shared/mac.hfv
pkill Xtightvnc
